version: v1
project: pet-reminder-api
services:
  backend:
    api:
      image: jzaefferer/pet-reminder-api
      domain: "pet-reminder-api.sloppy.zone"
      port: 7777
      instances: 1
      mem: 128
      env:
        - PORT: "7777"
        - COUCHDB_URL: http://db.backend.pet-reminder-api:5984
      dependencies:
        - "db"
    db:
      image: couchdb:1.7.1
      domain: "pet-reminder-api-db.sloppy.zone"
      port: 5984
      mem: 256
      volumes:
        - container_path: /usr/local/var/lib/couchdb
